name: ESLint CI
on: [push, pull_request]
permissions: {}

jobs:
    eslint:
        name: Run ESLint checks
        runs-on: ubuntu-latest
        permissions:
            contents: read

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Enable corepack
              run: corepack enable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Build packages
              run: yarn build

            - name: Check with ESLint
              run: yarn eslint
